### ISSUE TITLE
Can't build: Unable to resolve asset ID for "dart:core"

### ISSUE THREAD

**Issue by davenotik** [localvoid/liquid#11]
Giving this a go. Can't build my test. Snippet:

```
Building vdom_fun... 
[Error from Factory on vdom_fun|web/boxes.dart]:
Unable to resolve asset ID for "dart:core"
Build error:
Transform Factory on vdom_fun|web/boxes.dart threw error: <rethrow>
Caused by Could not resolve dart:core
#0      AnalysisTask._safelyPerform (package:analyzer/src/generated/engine.dart:6762:7)
#1      AnalysisTask.perform (package:analyzer/src/generated/engine.dart:6727:21)
...
```

**Comment by localvoid** [comment]
Yes, it is the same error. I am not sure why this is happening, cannot reproduce this error on Linux/Dart 1.8.5.

Maybe I am missing something, or doing something stupid with "analyzer", or "code_transformers" packages, I don't have too much experience with this packages.
